# See README_... in this folder for more information

# To be called when we get new users through AD B2C
### 201, currently 404 since user probably already seeded
POST https://{{host}}/api/userprofiles HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

# To be called to create devusers
### 201
POST https://{{host}}/api/userprofiles/devuser HTTP/1.1
Authorization: 1514BF2C-4F9F-4E97-B452-877695B1FF2C
content-type: application/json

{
    "email": "test1@lifecouple.net"
}

### 404 (user already existing, seeded)
POST https://{{host}}/api/userprofiles/devuser HTTP/1.1
Authorization: 1514BF2C-4F9F-4E97-B452-877695B1FF2C
content-type: application/json

{
    "email": "pgrimskog@lifecouple.net"
}

### 401 - no auth token
POST https://{{host}}/api/userprofiles HTTP/1.1
content-type: application/json

{
}